[package]
name = "ml_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false }
ml_core = { path = "../../core"}
serde = { version = "1.0", default-features = false, features = ["alloc"] }
