[package]
version = "0.1.0"
name = "sp1-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "3.0.0-rc4"
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
ml_lib = { path = "../lib" }
